# Generated by Django 5.2.9 on 2025-12-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corrida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('corrida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corrida.corrida')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
